<a href="https://colab.research.google.com/github/19PA1A0259/AI-LAB/blob/master/Experiment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Different ways to create numpy arrays.

In [32]:
[]
import numpy as np
p=np.array([1,2,3])
print(p)
p=np.array([[1,2,3],[10,20,30]])
print(p)

[1 2 3]
[[ 1  2  3]
 [10 20 30]]


2) ADD, REMOVE,MODIFY array elements in array.

Add

In [33]:
a=np.array([1,2,3]) 
b=np.append(a,[96,98,100]) 
print(b)

[  1   2   3  96  98 100]


REMOVE

In [34]:
x=np.delete(a,2)
print(x)

[1 2]


MODIFY

In [35]:
x[x<2]=-1
print(x)

[-1  2]


 3) Arthematic operations on numpy array []

In [36]:
import numpy as np
L=([9,8,7])
m=([7,8,9])
num_sum=np.add(L,m)
num_diff=np.subtract(L,m)
num_prod=np.multiply(L,m)
num_quo=np.divide(L,m)
num_mod=np.mod(L,m)
num_pow=np.power(L,m)
print(num_sum) 
print(num_diff) 
print(num_prod) 
print(num_quo) 
print(num_mod)

[16 16 16]
[ 2  0 -2]
[63 64 63]
[1.28571429 1.         0.77777778]
[2 0 7]


 4) Slicing and iterating of numpy array.

Slicing

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[1:8])

[2 3 4 5 6 7 8]


Iterating

In [29]:
for x in arr:
  print(x)

1
2
3
4
5
6
7
8


5)matrix operations on numpy arrays

In [30]:
import numpy as np
s=np.array([[1,2],[3,4]])
t=np.array([[5,6],[7,8]])
print(np.add(s,t))
print(np.subtract(s,t)) 
print(np.divide(s,t))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
